name: Node CI

on:
  push:
    branches:
      - main
      - "releases/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: npm install, build, and test
        run: |
          npm install
          npm run build
