name: Node CI

on:
  push:
    branches:
      - main
      - "releases/**"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: npm install, build, and test
        run: |
          npm clean-install
          npm run build
          npm run test
